[book]
title = "CView"
authors = ["Rudra Banerjee"]
language = "en"
src = "src"

[preprocessor.admonish]
command = "mdbook-admonish"

# 2. Output Configuration
[output.html]
theme = "theme"
additional-css = ["mdbook-admonish.css", "custom.css"]
additional-js  = ["custom.js"]
git-repository-url = "https://github.com/mavensgroup/cview"
site-url = "/cview/"
