[book]
title = "CView"
authors = ["Rudra Banerjee"]
language = "en"
src = "src"

[preprocessor.admonish]

# 2. Output Configuration
[output.html]
theme = "theme"
additional-css = ["src/mdbook-admonish.css", "src/custom.css", ]
additional-js  = ["src/custom.js"]
git-repository-url = "https://github.com/mavensgroup/cview"
site-url = "/cview/"
